import './global.css';

export const metadata = {
  title: 'Welcome to test-app',
  description: 'Generated by create-nx-workspace',
};

import '@stone-payments/jade-design-tokens/stone/fonts.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="jade">{children}</body>
    </html>
  );
}
